name: Create branch test

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: >
          Name of the repo containing tests. Repo should be in ballerina-platform org.
          Example- module-ballerina-http
        required: true
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup custom image
        id: image
        run: |
          git checkout -b ${{ github.event.inputs.repo-name }}
          git remote -v
          git push origin ${{ github.event.inputs.repo-name }}
