name: Create branch test

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: >
          Name of the repo containing tests. Repo should be in ballerina-platform org.
          Example- module-ballerina-http
        required: true
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup custom image
        id: image
        run: |
          git clone https://xlight05:${{ secrets.GITHUB_TOKEN }}@github.com/xlight05/ballerina-performance-cloud
          timestamp=$(date +%s -u)
          branch_name="nightly-${timestamp}"
          git checkout -b ${branch_name}
          git push origin ${branch_name}
