name: Test VM Create

on:
  workflow_dispatch:
    inputs:
      vmName:
        description: 'VM Name'
        default: 'test-vm'
        required: false
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Create VM Instance
      id: vminstance
      uses: azure/CLI@v1
      with:
        azcliversion: "agentazcliversion"
        inlineScript: |
          az vm create --resource-group "${{ secrets.CLUSTER_RESOURCE_GROUP }}"  --name "${{ github.event.inputs.vmName }}"  --admin-username "${{ secrets.VM_USER }}" --admin-password "${{ secrets.VM_PWD }}" --location  eastus \
          --image "Canonical:UbuntuServer:18.04-LTS:latest" --size "Standard_F4s_v2"
          echo "::set-output name=ip-address::$(az vm show -d -g "${{ secrets.CLUSTER_RESOURCE_GROUP }}" -n "${{ github.event.inputs.vmName }}" --query publicIps -o tsv)"
    - name: Create file
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.vminstance.outputs.ip-address }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PWD }}
        command_timeout: '180m' #3 hours
        timeout: 300s #5 mins
        script: |
            echo "hello" > test.txt
    - name: copy file to host
      uses: appleboy/scp-action@master
      with:
        host: ${{ steps.vminstance.outputs.ip-address }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PWD }}
        port: 22
        source: "test.txt"
        target: "test.txt"
    - name: Cat test
      run: |
          ls -la
          cat test.txt