name: Test VM Create

on:
  workflow_dispatch:
    inputs:
      vmName:
        description: 'VM Name'
        default: ''
        required: false
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: copy file to host
      run: |
        echo "${{ github.event.inputs.vmName }}"